name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: mon-runner205

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd /opt/git/mon && git clone git@github.com:JodyBoyy/mon.git && git pull origin master && docker compose up -d --build && docker compose restart
